# Import libraries 

In [13]:
#pip install -U scikit-learn
#!pip install xgboost


'pip' is not recognized as an internal or external command,
operable program or batch file.


In [39]:
import numpy as np
import pandas as pd 
#import xgboost as xgb 

# Read the Data

In [40]:
file_path = 'C:/Users/Maryam/Desktop/Job applications/Portfolio/DataSets/classification_data.csv'
dataset = pd.read_csv(file_path)
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
 

# k-Fold Cross Validation

In [112]:
def cross_validation(classifier, x_train, y_train):
    from sklearn.model_selection import cross_val_score
    accuracies = cross_val_score(estimator = classifier, X=x_train, y=y_train, cv = 10)
    accuracies_mean = accuracies.mean()
    accuracies_std = accuracies.std()
    return accuracies_mean, accuracies_std 

# Grid Search

In [113]:
def parameters_estimation(classifier, parameters, accuracy, x_train, y_train):
    from sklearn.model_selection import GridSearchCV

    # Create a grid search object
    grid_search = GridSearchCV(estimator=classifier, param_grid=parameters, scoring= accuracy, cv=10, n_jobs=-1)

    # Perform the grid search on your training data
    grid_search.fit(x_train, y_train)

    # Get the best hyperparameters and estimator
    best_regressor = grid_search.best_estimator_
    best_param = grid_search.best_params_
    
    return best_param

# Model Evaluation

In [114]:
def model_evaluation(updated_classifier, x_test, y_test):
    # to show the number of correct and incorrect prediction 
    # Making the Confusion Matrix 
    from sklearn.metrics import confusion_matrix, accuracy_score
    y_pred = updated_classifier.predict(x_test) 
    cm = confusion_matrix(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)

    return cm, accuracy

# Methods

## Logistic Regression 

In [115]:
# define a function for a Logistic Regression (LR) method
def Logistic_Regression():
    # create a LR classifier and train it on the training set
    # random state: 
    from sklearn.linear_model import LogisticRegression 
    classifier = LogisticRegression(random_state = 0)
    classifier.fit(x_train, y_train)

   # call the cross_validation function to return the mean and the standard deviation of the accuracies of all sub-sets
    accuracies_mean, accuracies_std = cross_validation(classifier, x_train, y_train)
    
    # call model_evaluation function to return the confusion matrix (cm) and the overall accuracy of the KNN method
    cm, accuracy = model_evaluation(classifier, x_test, y_test)

    # the LR function returns the following values
    return accuracies_mean, accuracies_std, cm, accuracy

# accuracies_mean_LR, accuracies_std_LR, cm_LR, accuracy_LR = Logistic_Regression()

## K-Nearest Neighbors Algorithm

In [116]:
# define a function for a K-Nearest Kneighbours method
def KNN():
    # create an SVR classifier and train it on the training set
    # n_neighbors:
    # metric
    # p  
    from sklearn.neighbors import KNeighborsClassifier
    classifier = KNeighborsClassifier(n_neighbors=5, metric= 'minkowski', p = 2)
    classifier.fit(x_train, y_train)

    # call the cross_validation function to return the mean and the standard deviation of the accuracies of all sub-sets
    accuracies_mean, accuracies_std = cross_validation(classifier, x_train, y_train)
    
    # define the parameters to be optimized in order to improve the accuracy of the method. 
    parameters = {'n_neighbors': [1, 5, 10, 20]}

    # call parameters_estimation function to return the best value of the parameters
    best_param = parameters_estimation(classifier, parameters, 'accuracy', x_train, y_train)
    best_n_neighbors = best_param['n_neighbors']
    # print the best hyperparameters
    print("Best Hyperparameters of KNN method:", best_param)
    

    # update the classifier using the best parameters return from parameters_estimation function
    updated_classifier = KNeighborsClassifier(n_neighbors=best_n_neighbors, metric= 'minkowski', p = 2)
    updated_classifier.fit(x_train, y_train)

    # call model_evaluation function to return the confusion matrix (cm) and the overall accuracy of the KNN method
    cm, accuracy = model_evaluation(classifier, x_test, y_test)


    # the KNN function returns the following values 
    return accuracies_mean, accuracies_std, cm, accuracy

# accuracies_mean_KNN, accuracies_std_KNN, cm_KNN, accuracy_KNN = KNN()



## Support Vector Regression (SVR)

In [124]:
def SVR():
    # create an SVR classifier and train it on the training set
    # kernel: 
    from sklearn.svm import SVC 
    classifier = SVC(kernel='rbf', random_state=0)
    classifier.fit(x_train, y_train)
        
    ###################################################################### Cross-Validation ##############################################################################
    # call the cross_validation function to return the mean and the standard deviation of the accuracies of all sub-sets
    accuracies_mean, accuracies_std = cross_validation(classifier, x_train, y_train)

    ################################################################### parameters_estimation #############################################################################
    # call parameters_estimation function to return the best value of the parameters 
    best_param = parameters_estimation(classifier, parameters, 'accuracy', x_train, y_train)
    best_kernel = best_param['kernel']
    print("Best Hyperparameters of SVR method:", best_param)
        
    # update the classifier using the best parameters returned from parameters_estimation (grid search)
    updated_classifier = SVC(kernel=best_kernel, random_state=0)
    updated_classifier.fit(x_train, y_train)

    ###################################################################### Model Evaluation ###############################################################################
    # call model_evaluation function to return the confusion matrix (cm) and the overall accuracy of the KNN method
    cm, accuracy = model_evaluation(classifier, x_test, y_test)

    return accuracies_mean, accuracies_std, cm, accuracy

accuracies_mean_SVR, accuracies_std_SVR, cm_SVR, accuracy_SVR = SVR() 



Best Hyperparameters of SVR method: {'C': 0.25, 'kernel': 'linear'}


## Decision Tree 

In [118]:
# define a function for a Decision Tree method
def Decision_Tree():
    # create a Decision Tree classifier and train it on the training set
    # criterion: 
    # random_state: 
    from sklearn.tree import DecisionTreeClassifier
    classifier = DecisionTreeClassifier(criterion='entropy', random_state=0)
    classifier.fit(x_train, y_train)

    # call the cross_validation function to return the mean and the standard deviation of the accuracies of all sub-sets
    accuracies_mean, accuracies_std = cross_validation(classifier, x_train, y_train)

    # define the parameters to be optimized in order to improve the accuracy of the method 
    parameters = {'criterion': ['gini', 'entropy']}
    
    # call parameters_estimation function to return the best value of the parameters 
    best_param = parameters_estimation(classifier, parameters, 'accuracy', x_train, y_train)
    print("Best Hyperparameters of Decision Tree method:", best_param)

    # update the classifier using the best parameters return from parameters_estimation function
    updated_classifier = DecisionTreeClassifier(criterion=best_param['criterion'], random_state=0)
    updated_classifier.fit(x_train, y_train)

    # to show the number of correct and incorrect prediction 
    # Making the Confusion Matrix 
    # call model_evaluation function to return the confusion matrix (cm) and the overall accuracy of the KNN method
    cm, accuracy = model_evaluation(classifier, x_test, y_test)

    # the Decision Tree function returns the following values 
    return accuracies_mean, accuracies_std, cm, accuracy

#accuracies_mean_DT, accuracies_std_DT, cm_DT, accuracy_DT = Decision_Tree()


## Random Forest Model

In [119]:
# define a function for a Random Forest method
def Random_Forest():
    # create a Random Forest classifier and train it on the training set
    # n_estimators
    # criterion:
    # random_state: 
    from sklearn.ensemble import RandomForestClassifier
    classifier = RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
    classifier.fit(x_train, y_train)

    # call the cross_validation function to return the mean and the standard deviation of the accuracies of all sub-sets
    accuracies_mean, accuracies_std = cross_validation(classifier, x_train, y_train)

    
    # define the parameters to be optimized in order to improve the accuracy of the method.  
    parameters = {'criterion': ['gini', 'entropy']}

    # call parameters_estimation function to return the best value of the parameters 
    best_param = parameters_estimation(classifier, parameters, 'accuracy', x_train, y_train)
    print("Best Hyperparameters of Random Forest method:", best_param)

    # update the classifier using the best parameters return from parameters_estimation function  
    updated_classifier = RandomForestClassifier(n_estimators = 10, criterion=best_param['criterion'], random_state=0)
    updated_classifier.fit(x_train, y_train)

    # to show the number of correct and incorrect prediction 
    # Making the Confusion Matrix 
    # call model_evaluation function to return the confusion matrix (cm) and the overall accuracy of the KNN method
    cm, accuracy = model_evaluation(classifier, x_test, y_test)

    # the Random Forest function returns the following values 
    return accuracies_mean, accuracies_std, cm, accuracy

# accuracies_mean_RF, accuracies_std_RF, cm_RF, accuracy_RF = Random_Forest()

## XGBoost 

In [120]:
# define a function for XGBoost method 
def XGBoost_method():

   # create an XGBoost classifier and train it using the training set 
   from xgboost import XGBRegressor
   classifier = XGBClassifier()
   classifier.fit(x_train, y_train)

   # call the cross_validation function to return the mean and the standard deviation of the accuracies of all sub-sets
   accuracies_mean, accuracies_std = cross_validation(classifier, x_train, y_train)

   # to show the number of correct and incorrect prediction 
   # Making the Confusion Matrix 
   # call model_evaluation function to return the confusion matrix (cm) and the overall accuracy of the KNN method
   cm, accuracy = model_evaluation(classifier, x_test, y_test)


   # the XGBoost function returns the following values 
   return accuracies_mean, accuracies_std, cm, accuracy

#accuracies_mean_XG, accuracies_std_XG, cm_XG, accuracy_XG = XGBoost_method()

# Models Ranking 

In [122]:
# to select the best model, the model functions are called to return the performance measures that are used to rank all the models from the most accurate to the least accurate.
# the measures are: the average mean of the cross validation accuracy, the standard deviation of the cross validation accuracy, the confusion materix and the overall accuracy
accuracies_mean_LR, accuracies_std_LR, cm_LR, accuracy_LR = Logistic_Regression() 
accuracies_mean_KNN, accuracies_std_KNN, cm_KNN, accuracy_KNN = KNN()
accuracies_mean_SVR, accuracies_std_SVR, cm_SVR, accuracy_SVR = SVR()
accuracies_mean_DT, accuracies_std_DT, cm_DT, accuracy_DT = Decision_Tree()
accuracies_mean_RF, accuracies_std_RF, cm_RF, accuracy_RF = Random_Forest()
#ccuracies_mean_XG, accuracies_std_XG, cm_XG, accuracy_XG = XGBoost_method()

# after running all the models, the performance measures are stored in dictonaries in order to be ranked    
accuracies_mean_dict = {'LR': accuracies_mean_LR, 'KNN': accuracies_mean_KNN, 'SVR': accuracies_mean_SVR, 'DT': accuracies_mean_DT, 'RF': accuracies_mean_RF}
accuracies_std_dict = {'LR': accuracies_std_LR, 'KNN': accuracies_std_KNN, 'SVR': accuracies_std_SVR, 'DT': accuracies_std_DT, 'RF': accuracies_std_RF}
cm_dict = {'LR': cm_LR, 'KNN': cm_KNN, 'SVR': cm_SVR, 'DT': cm_DT, 'RF': cm_RF}
accuracy_dict = {'LR': accuracy_LR, 'KNN': accuracy_KNN, 'SVR': accuracy_SVR, 'DT': accuracy_DT, 'RF': accuracy_RF}

# the dictories are ranked from the highest to the lowest. 
sorted_accuracies_mean = dict(sorted(accuracies_mean_dict.items(), key=lambda item: item[1], reverse=True))
sorted_accuracies_std = dict(sorted(accuracies_std_dict.items(), key=lambda item: item[1], reverse=False))
sorted_accuracy = dict(sorted(accuracy_dict.items(), key=lambda item: item[1], reverse=True))


Best Hyperparameters of KNN method: {'n_neighbors': 10}
Best Hyperparameters of SVR method: {'C': 0.25, 'kernel': 'linear'}
Best Hyperparameters of Decision Tree method: {'criterion': 'entropy'}
Best Hyperparameters of Random Forest method: {'criterion': 'gini'}


# Analysis and Recommendations

In [123]:
# the first model in each dictonary is the best one 
print("Confusion Matrix are:")
print("Logistic Regression")
print(cm_LR)
print("KNN")
print(cm_KNN)
print("Support Vector Regression")
print(cm_SVR)
print("Decision Tree")
print(cm_DT)
print("Random Forest")
print(cm_RF)
print("Sorted overall accuracy are:", sorted_accuracy)
print("Sorted cross-validation mean accuracies are:", sorted_accuracies_mean)
print("Sorted standard deviation of the cross-validation accuracies are:", sorted_accuracies_std)

Confusion Matrix are:
Logistic Regression
[[84  3]
 [ 3 47]]
KNN
[[83  4]
 [ 2 48]]
Support Vector Regression
[[82  5]
 [ 1 49]]
Decision Tree
[[85  2]
 [ 2 48]]
Random Forest
[[84  3]
 [ 3 47]]
Sorted overall accuracy are: {'DT': 0.9708029197080292, 'LR': 0.9562043795620438, 'KNN': 0.9562043795620438, 'SVR': 0.9562043795620438, 'RF': 0.9562043795620438}
Sorted cross-validation mean accuracies are: {'LR': 0.967003367003367, 'KNN': 0.967003367003367, 'SVR': 0.9652525252525253, 'RF': 0.9615151515151515, 'DT': 0.9524242424242425}
Sorted standard deviation of the cross-validation accuracies are: {'KNN': 0.017941421104663395, 'SVR': 0.01906913288410605, 'LR': 0.019697976894447813, 'RF': 0.0239014792077341, 'DT': 0.024905835653388116}
